// <auto-generated />
using System;
using Demo2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo2.Migrations
{
    [DbContext(typeof(Demo2Context))]
    partial class Demo2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Demo2.Models.Mark", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentRollNumber");

                    b.Property<int>("SubjectMark");

                    b.Property<string>("SubjectName");

                    b.HasKey("ID");

                    b.HasIndex("StudentRollNumber");

                    b.ToTable("Marks");

                    b.HasData(
                        new { ID = 1, StudentRollNumber = "A001", SubjectMark = 20, SubjectName = "Java" },
                        new { ID = 2, StudentRollNumber = "A002", SubjectMark = 20, SubjectName = "C#" },
                        new { ID = 3, StudentRollNumber = "A003", SubjectMark = 20, SubjectName = "PHP" }
                    );
                });

            modelBuilder.Entity("Demo2.Models.Student", b =>
                {
                    b.Property<string>("RollNumber")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("Status");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("RollNumber");

                    b.ToTable("Student");

                    b.HasData(
                        new { RollNumber = "A001", CreatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 403, DateTimeKind.Local), Email = "tinhgiang9898@gmail.com", FirstName = "Giang", LastName = "Tinh", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 404, DateTimeKind.Local) },
                        new { RollNumber = "A002", CreatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 404, DateTimeKind.Local), Email = "ly@gmail.com", FirstName = "Huong", LastName = "Ly", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 404, DateTimeKind.Local) },
                        new { RollNumber = "A003", CreatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 404, DateTimeKind.Local), Email = "thanhtung@gmail.com", FirstName = "Thanh", LastName = "Tung", Status = 1, UpdatedAt = new DateTime(2018, 11, 6, 19, 57, 14, 404, DateTimeKind.Local) }
                    );
                });

            modelBuilder.Entity("Demo2.Models.Mark", b =>
                {
                    b.HasOne("Demo2.Models.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentRollNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
